import type { BlockTemplate, ColorScheme } from '../types';
import { FieldType } from '../types';

// ========== 预设块模板（ID 固定，确保 JSON 导入导出可恢复） ==========

// ---- 基础组件（单字段基础元素） ----
export const presetBlockTemplates: BlockTemplate[] = [
  {
    id: 'tpl-text',
    name: '文本框',
    category: '基础组件',
    isPreset: true,
    createdAt: 0,
    updatedAt: 0,
    fields: [
      { id: 'text-content', name: '内容', type: FieldType.RichText, order: 0, defaultValue: '', required: true, placeholder: '输入文本内容' },
    ],
  },
  {
    id: 'tpl-link',
    name: '链接',
    category: '基础组件',
    isPreset: true,
    createdAt: 0,
    updatedAt: 0,
    fields: [
      { id: 'link-url', name: '链接地址', type: FieldType.Link, order: 0, defaultValue: '', required: true, placeholder: '输入链接地址' },
    ],
  },
  {
    id: 'tpl-date',
    name: '日期',
    category: '基础组件',
    isPreset: true,
    createdAt: 0,
    updatedAt: 0,
    fields: [
      { id: 'date-value', name: '日期', type: FieldType.Date, order: 0, defaultValue: '', required: true, placeholder: '选择日期' },
    ],
  },
  {
    id: 'tpl-rating',
    name: '评分',
    category: '基础组件',
    isPreset: true,
    createdAt: 0,
    updatedAt: 0,
    fields: [
      { id: 'rating-value', name: '评分', type: FieldType.Rating, order: 0, defaultValue: '3', required: false, placeholder: '' },
    ],
  },
];

// ========== 预设色彩方案 ==========
export const presetColorSchemes: ColorScheme[] = [
  {
    id: 'cs-professional-blue',
    name: '沉稳蓝',
    primary: '#1a56db',
    secondary: '#d1e0ff',
    background: '#ffffff',
    blockBackground: '#f8faff',
    textPrimary: '#1f2937',
    textSecondary: '#4b5563',
    textMuted: '#9ca3af',
    accent: '#2563eb',
    isPreset: true,
  },
  {
    id: 'cs-elegant-dark',
    name: '优雅深灰',
    primary: '#374151',
    secondary: '#e5e7eb',
    background: '#ffffff',
    blockBackground: '#f9fafb',
    textPrimary: '#111827',
    textSecondary: '#4b5563',
    textMuted: '#9ca3af',
    accent: '#6366f1',
    isPreset: true,
  },
  {
    id: 'cs-fresh-green',
    name: '清新绿',
    primary: '#059669',
    secondary: '#d1fae5',
    background: '#ffffff',
    blockBackground: '#f0fdf4',
    textPrimary: '#1f2937',
    textSecondary: '#4b5563',
    textMuted: '#9ca3af',
    accent: '#10b981',
    isPreset: true,
  },
  {
    id: 'cs-warm-orange',
    name: '活力橙',
    primary: '#ea580c',
    secondary: '#ffedd5',
    background: '#ffffff',
    blockBackground: '#fff7ed',
    textPrimary: '#1f2937',
    textSecondary: '#4b5563',
    textMuted: '#9ca3af',
    accent: '#f97316',
    isPreset: true,
  },
  {
    id: 'cs-creative-purple',
    name: '创意紫',
    primary: '#7c3aed',
    secondary: '#ede9fe',
    background: '#ffffff',
    blockBackground: '#faf5ff',
    textPrimary: '#1f2937',
    textSecondary: '#4b5563',
    textMuted: '#9ca3af',
    accent: '#8b5cf6',
    isPreset: true,
  },
  {
    id: 'cs-tech-cyan',
    name: '科技青',
    primary: '#0891b2',
    secondary: '#cffafe',
    background: '#ffffff',
    blockBackground: '#ecfeff',
    textPrimary: '#1f2937',
    textSecondary: '#4b5563',
    textMuted: '#9ca3af',
    accent: '#06b6d4',
    isPreset: true,
  },
  {
    id: 'cs-minimal-bw',
    name: '极简黑白',
    primary: '#111827',
    secondary: '#f3f4f6',
    background: '#ffffff',
    blockBackground: '#fafafa',
    textPrimary: '#111827',
    textSecondary: '#374151',
    textMuted: '#9ca3af',
    accent: '#111827',
    isPreset: true,
  },
  {
    id: 'cs-rose-pink',
    name: '玫瑰粉',
    primary: '#e11d48',
    secondary: '#ffe4e6',
    background: '#ffffff',
    blockBackground: '#fff1f2',
    textPrimary: '#1f2937',
    textSecondary: '#4b5563',
    textMuted: '#9ca3af',
    accent: '#f43f5e',
    isPreset: true,
  },
];
