import { v4 as uuid } from 'uuid';
import type { BlockTemplate, ColorScheme, LayoutConfig } from '../types';
import { FieldType } from '../types';

// ========== 预设块模板 ==========
export const presetBlockTemplates: BlockTemplate[] = [
  {
    id: uuid(),
    name: '头部信息',
    category: '头部',
    isPreset: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    fields: [
      { id: uuid(), name: '头像', type: FieldType.Image, order: 0, defaultValue: '', required: false, placeholder: '上传头像' },
      { id: uuid(), name: '姓名', type: FieldType.Text, order: 1, defaultValue: '', required: true, placeholder: '输入姓名' },
      { id: uuid(), name: '职位', type: FieldType.Text, order: 2, defaultValue: '', required: false, placeholder: '输入目标职位' },
      { id: uuid(), name: '一句话简介', type: FieldType.Text, order: 3, defaultValue: '', required: false, placeholder: '一句话介绍自己' },
      { id: uuid(), name: '电话', type: FieldType.Text, order: 4, defaultValue: '', required: false, placeholder: '输入电话号码' },
      { id: uuid(), name: '邮箱', type: FieldType.Text, order: 5, defaultValue: '', required: false, placeholder: '输入邮箱地址' },
      { id: uuid(), name: '地址', type: FieldType.Text, order: 6, defaultValue: '', required: false, placeholder: '输入地址' },
      { id: uuid(), name: '个人网站', type: FieldType.Link, order: 7, defaultValue: '', required: false, placeholder: '输入个人网站链接' },
    ],
  },
  {
    id: uuid(),
    name: '基本信息',
    category: '基础',
    isPreset: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    fields: [
      { id: uuid(), name: '姓名', type: FieldType.Text, order: 0, defaultValue: '', required: true, placeholder: '输入姓名' },
      { id: uuid(), name: '头像', type: FieldType.Image, order: 1, defaultValue: '', required: false, placeholder: '上传头像' },
      { id: uuid(), name: '电话', type: FieldType.Text, order: 2, defaultValue: '', required: false, placeholder: '输入电话号码' },
      { id: uuid(), name: '邮箱', type: FieldType.Text, order: 3, defaultValue: '', required: false, placeholder: '输入邮箱地址' },
      { id: uuid(), name: '地址', type: FieldType.Text, order: 4, defaultValue: '', required: false, placeholder: '输入地址' },
      { id: uuid(), name: '个人网站', type: FieldType.Link, order: 5, defaultValue: '', required: false, placeholder: '输入个人网站链接' },
    ],
  },
  {
    id: uuid(),
    name: '工作经历',
    category: '经历',
    isPreset: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    fields: [
      { id: uuid(), name: '公司名', type: FieldType.Text, order: 0, defaultValue: '', required: true, placeholder: '输入公司名称' },
      { id: uuid(), name: '职位', type: FieldType.Text, order: 1, defaultValue: '', required: true, placeholder: '输入职位名称' },
      { id: uuid(), name: '开始时间', type: FieldType.Date, order: 2, defaultValue: '', required: true, placeholder: '选择开始时间' },
      { id: uuid(), name: '结束时间', type: FieldType.Date, order: 3, defaultValue: '', required: false, placeholder: '选择结束时间' },
      { id: uuid(), name: '是否至今', type: FieldType.Switch, order: 4, defaultValue: 'false', required: false, placeholder: '' },
      { id: uuid(), name: '公司简介', type: FieldType.TextArea, order: 5, defaultValue: '', required: false, placeholder: '输入公司简介' },
      { id: uuid(), name: '技能标签', type: FieldType.TagList, order: 6, defaultValue: '', required: false, placeholder: '输入技能标签，回车添加' },
      { id: uuid(), name: '工作描述', type: FieldType.RichText, order: 7, defaultValue: '', required: true, placeholder: '输入工作描述' },
    ],
  },
  {
    id: uuid(),
    name: '教育背景',
    category: '教育',
    isPreset: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    fields: [
      { id: uuid(), name: '学校', type: FieldType.Text, order: 0, defaultValue: '', required: true, placeholder: '输入学校名称' },
      { id: uuid(), name: '学位', type: FieldType.Select, order: 1, defaultValue: '', required: true, placeholder: '选择学位', options: ['大专', '本科', '硕士', '博士', 'MBA', '其他'] },
      { id: uuid(), name: '专业', type: FieldType.Text, order: 2, defaultValue: '', required: true, placeholder: '输入专业' },
      { id: uuid(), name: 'GPA', type: FieldType.Text, order: 3, defaultValue: '', required: false, placeholder: '输入GPA' },
      { id: uuid(), name: '开始时间', type: FieldType.Date, order: 4, defaultValue: '', required: true, placeholder: '选择开始时间' },
      { id: uuid(), name: '结束时间', type: FieldType.Date, order: 5, defaultValue: '', required: false, placeholder: '选择结束时间' },
      { id: uuid(), name: '课程', type: FieldType.TagList, order: 6, defaultValue: '', required: false, placeholder: '输入课程，回车添加' },
      { id: uuid(), name: '荣誉', type: FieldType.TextArea, order: 7, defaultValue: '', required: false, placeholder: '输入荣誉奖项' },
    ],
  },
  {
    id: uuid(),
    name: '项目经验',
    category: '经历',
    isPreset: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    fields: [
      { id: uuid(), name: '项目名', type: FieldType.Text, order: 0, defaultValue: '', required: true, placeholder: '输入项目名称' },
      { id: uuid(), name: '角色', type: FieldType.Text, order: 1, defaultValue: '', required: false, placeholder: '输入项目角色' },
      { id: uuid(), name: '时间', type: FieldType.Text, order: 2, defaultValue: '', required: false, placeholder: '如 2023.01 - 2023.06' },
      { id: uuid(), name: '技术栈', type: FieldType.TagList, order: 3, defaultValue: '', required: false, placeholder: '输入技术栈，回车添加' },
      { id: uuid(), name: '描述', type: FieldType.RichText, order: 4, defaultValue: '', required: true, placeholder: '输入项目描述' },
      { id: uuid(), name: '链接', type: FieldType.Link, order: 5, defaultValue: '', required: false, placeholder: '输入项目链接' },
      { id: uuid(), name: '截图', type: FieldType.Image, order: 6, defaultValue: '', required: false, placeholder: '上传项目截图' },
    ],
  },
  {
    id: uuid(),
    name: '技能',
    category: '基础',
    isPreset: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    fields: [
      { id: uuid(), name: '技能名', type: FieldType.Text, order: 0, defaultValue: '', required: true, placeholder: '输入技能名称' },
      { id: uuid(), name: '熟练度', type: FieldType.Rating, order: 1, defaultValue: '3', required: false, placeholder: '' },
    ],
  },
  {
    id: uuid(),
    name: '自我总结',
    category: '基础',
    isPreset: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    fields: [
      { id: uuid(), name: '描述', type: FieldType.TextArea, order: 0, defaultValue: '', required: true, placeholder: '输入自我总结' },
    ],
  },
  {
    id: uuid(),
    name: '证书',
    category: '其他',
    isPreset: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    fields: [
      { id: uuid(), name: '名称', type: FieldType.Text, order: 0, defaultValue: '', required: true, placeholder: '输入证书名称' },
      { id: uuid(), name: '颁发机构', type: FieldType.Text, order: 1, defaultValue: '', required: false, placeholder: '输入颁发机构' },
      { id: uuid(), name: '时间', type: FieldType.Date, order: 2, defaultValue: '', required: false, placeholder: '选择获得时间' },
      { id: uuid(), name: '编号', type: FieldType.Text, order: 3, defaultValue: '', required: false, placeholder: '输入证书编号' },
      { id: uuid(), name: '链接', type: FieldType.Link, order: 4, defaultValue: '', required: false, placeholder: '输入证书链接' },
    ],
  },
  {
    id: uuid(),
    name: '语言',
    category: '其他',
    isPreset: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    fields: [
      { id: uuid(), name: '语言', type: FieldType.Text, order: 0, defaultValue: '', required: true, placeholder: '输入语言' },
      { id: uuid(), name: '听说', type: FieldType.Select, order: 1, defaultValue: '', required: false, placeholder: '选择听说等级', options: ['精通', '熟练', '一般', '入门'] },
      { id: uuid(), name: '读写', type: FieldType.Select, order: 2, defaultValue: '', required: false, placeholder: '选择读写等级', options: ['精通', '熟练', '一般', '入门'] },
    ],
  },
  {
    id: uuid(),
    name: '兴趣爱好',
    category: '其他',
    isPreset: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    fields: [
      { id: uuid(), name: '标签', type: FieldType.TagList, order: 0, defaultValue: '', required: true, placeholder: '输入兴趣爱好，回车添加' },
    ],
  },
];

// ========== 预设色彩方案 ==========
export const presetColorSchemes: ColorScheme[] = [
  {
    id: 'cs-professional-blue',
    name: '沉稳蓝',
    primary: '#1a56db',
    secondary: '#d1e0ff',
    background: '#ffffff',
    blockBackground: '#f8faff',
    textPrimary: '#1f2937',
    textSecondary: '#4b5563',
    textMuted: '#9ca3af',
    accent: '#2563eb',
    isPreset: true,
  },
  {
    id: 'cs-elegant-dark',
    name: '优雅深灰',
    primary: '#374151',
    secondary: '#e5e7eb',
    background: '#ffffff',
    blockBackground: '#f9fafb',
    textPrimary: '#111827',
    textSecondary: '#4b5563',
    textMuted: '#9ca3af',
    accent: '#6366f1',
    isPreset: true,
  },
  {
    id: 'cs-fresh-green',
    name: '清新绿',
    primary: '#059669',
    secondary: '#d1fae5',
    background: '#ffffff',
    blockBackground: '#f0fdf4',
    textPrimary: '#1f2937',
    textSecondary: '#4b5563',
    textMuted: '#9ca3af',
    accent: '#10b981',
    isPreset: true,
  },
  {
    id: 'cs-warm-orange',
    name: '活力橙',
    primary: '#ea580c',
    secondary: '#ffedd5',
    background: '#ffffff',
    blockBackground: '#fff7ed',
    textPrimary: '#1f2937',
    textSecondary: '#4b5563',
    textMuted: '#9ca3af',
    accent: '#f97316',
    isPreset: true,
  },
  {
    id: 'cs-creative-purple',
    name: '创意紫',
    primary: '#7c3aed',
    secondary: '#ede9fe',
    background: '#ffffff',
    blockBackground: '#faf5ff',
    textPrimary: '#1f2937',
    textSecondary: '#4b5563',
    textMuted: '#9ca3af',
    accent: '#8b5cf6',
    isPreset: true,
  },
  {
    id: 'cs-tech-cyan',
    name: '科技青',
    primary: '#0891b2',
    secondary: '#cffafe',
    background: '#ffffff',
    blockBackground: '#ecfeff',
    textPrimary: '#1f2937',
    textSecondary: '#4b5563',
    textMuted: '#9ca3af',
    accent: '#06b6d4',
    isPreset: true,
  },
  {
    id: 'cs-minimal-bw',
    name: '极简黑白',
    primary: '#111827',
    secondary: '#f3f4f6',
    background: '#ffffff',
    blockBackground: '#fafafa',
    textPrimary: '#111827',
    textSecondary: '#374151',
    textMuted: '#9ca3af',
    accent: '#111827',
    isPreset: true,
  },
  {
    id: 'cs-rose-pink',
    name: '玫瑰粉',
    primary: '#e11d48',
    secondary: '#ffe4e6',
    background: '#ffffff',
    blockBackground: '#fff1f2',
    textPrimary: '#1f2937',
    textSecondary: '#4b5563',
    textMuted: '#9ca3af',
    accent: '#f43f5e',
    isPreset: true,
  },
];

// ========== 预设布局 ==========
export const presetLayouts: { name: string; description: string; config: LayoutConfig }[] = [
  {
    name: '经典单栏',
    description: '经典叙事型，适合管理岗',
    config: {
      type: 'single',
      columnRatio: [100, 0],
      headerStyle: 'center',
      density: 'standard',
      pageSize: { name: 'A4', width: 210, height: 297 },
      pageMargin: { top: 15, right: 20, bottom: 15, left: 20 },
      pageBreakStrategy: 'auto',
    },
  },
  {
    name: '技术双栏',
    description: '左栏技能+证书，右栏经历，适合技术岗',
    config: {
      type: 'double',
      columnRatio: [30, 70],
      headerStyle: 'left-align',
      density: 'compact',
      pageSize: { name: 'A4', width: 210, height: 297 },
      pageMargin: { top: 12, right: 15, bottom: 12, left: 15 },
      pageBreakStrategy: 'force-one',
    },
  },
  {
    name: '创意设计',
    description: '双栏带头像，适合设计类岗位',
    config: {
      type: 'double',
      columnRatio: [35, 65],
      headerStyle: 'with-avatar',
      density: 'spacious',
      pageSize: { name: 'A4', width: 210, height: 297 },
      pageMargin: { top: 20, right: 20, bottom: 20, left: 20 },
      pageBreakStrategy: 'auto',
    },
  },
  {
    name: '紧凑一页',
    description: '双栏紧凑布局，适合内容较多的简历',
    config: {
      type: 'double',
      columnRatio: [25, 75],
      headerStyle: 'left-align',
      density: 'compact',
      pageSize: { name: 'A4', width: 210, height: 297 },
      pageMargin: { top: 10, right: 12, bottom: 10, left: 12 },
      pageBreakStrategy: 'force-one',
    },
  },
  {
    name: '功能混合',
    description: '页头通栏+下方双栏，中西结合',
    config: {
      type: 'mixed',
      columnRatio: [35, 65],
      headerStyle: 'center',
      density: 'standard',
      pageSize: { name: 'A4', width: 210, height: 297 },
      pageMargin: { top: 15, right: 18, bottom: 15, left: 18 },
      pageBreakStrategy: 'auto',
    },
  },
];
