import type { BlockTemplate, ColorScheme } from '../types';
import { FieldType } from '../types';

// ========== 预设块模板（ID 固定，确保 JSON 导入导出可恢复） ==========
export const presetBlockTemplates: BlockTemplate[] = [
  {
    id: 'tpl-head',
    name: '头部信息',
    category: '头部',
    isPreset: true,
    createdAt: 0,
    updatedAt: 0,
    fields: [
      { id: 'head-avatar', name: '头像', type: FieldType.Image, order: 0, defaultValue: '', required: false, placeholder: '上传头像' },
      { id: 'head-name', name: '姓名', type: FieldType.Text, order: 1, defaultValue: '', required: true, placeholder: '输入姓名' },
      { id: 'head-title', name: '职位', type: FieldType.Text, order: 2, defaultValue: '', required: false, placeholder: '输入目标职位' },
      { id: 'head-bio', name: '一句话简介', type: FieldType.Text, order: 3, defaultValue: '', required: false, placeholder: '一句话介绍自己' },
      { id: 'head-phone', name: '电话', type: FieldType.Text, order: 4, defaultValue: '', required: false, placeholder: '输入电话号码' },
      { id: 'head-email', name: '邮箱', type: FieldType.Text, order: 5, defaultValue: '', required: false, placeholder: '输入邮箱地址' },
      { id: 'head-address', name: '地址', type: FieldType.Text, order: 6, defaultValue: '', required: false, placeholder: '输入地址' },
      { id: 'head-website', name: '个人网站', type: FieldType.Link, order: 7, defaultValue: '', required: false, placeholder: '输入个人网站链接' },
    ],
  },
  {
    id: 'tpl-basic',
    name: '基本信息',
    category: '基础',
    isPreset: true,
    createdAt: 0,
    updatedAt: 0,
    fields: [
      { id: 'basic-name', name: '姓名', type: FieldType.Text, order: 0, defaultValue: '', required: true, placeholder: '输入姓名' },
      { id: 'basic-avatar', name: '头像', type: FieldType.Image, order: 1, defaultValue: '', required: false, placeholder: '上传头像' },
      { id: 'basic-phone', name: '电话', type: FieldType.Text, order: 2, defaultValue: '', required: false, placeholder: '输入电话号码' },
      { id: 'basic-email', name: '邮箱', type: FieldType.Text, order: 3, defaultValue: '', required: false, placeholder: '输入邮箱地址' },
      { id: 'basic-address', name: '地址', type: FieldType.Text, order: 4, defaultValue: '', required: false, placeholder: '输入地址' },
      { id: 'basic-website', name: '个人网站', type: FieldType.Link, order: 5, defaultValue: '', required: false, placeholder: '输入个人网站链接' },
    ],
  },
  {
    id: 'tpl-work',
    name: '工作经历',
    category: '经历',
    isPreset: true,
    createdAt: 0,
    updatedAt: 0,
    fields: [
      { id: 'work-company', name: '公司名', type: FieldType.Text, order: 0, defaultValue: '', required: true, placeholder: '输入公司名称' },
      { id: 'work-position', name: '职位', type: FieldType.Text, order: 1, defaultValue: '', required: true, placeholder: '输入职位名称' },
      { id: 'work-start', name: '开始时间', type: FieldType.Date, order: 2, defaultValue: '', required: true, placeholder: '选择开始时间' },
      { id: 'work-end', name: '结束时间', type: FieldType.Date, order: 3, defaultValue: '', required: false, placeholder: '选择结束时间' },
      { id: 'work-current', name: '是否至今', type: FieldType.Switch, order: 4, defaultValue: 'false', required: false, placeholder: '' },
      { id: 'work-desc-company', name: '公司简介', type: FieldType.TextArea, order: 5, defaultValue: '', required: false, placeholder: '输入公司简介' },
      { id: 'work-tags', name: '技能标签', type: FieldType.TagList, order: 6, defaultValue: '', required: false, placeholder: '输入技能标签，回车添加' },
      { id: 'work-description', name: '工作描述', type: FieldType.RichText, order: 7, defaultValue: '', required: true, placeholder: '输入工作描述' },
    ],
  },
  {
    id: 'tpl-edu',
    name: '教育背景',
    category: '教育',
    isPreset: true,
    createdAt: 0,
    updatedAt: 0,
    fields: [
      { id: 'edu-school', name: '学校', type: FieldType.Text, order: 0, defaultValue: '', required: true, placeholder: '输入学校名称' },
      { id: 'edu-degree', name: '学位', type: FieldType.Select, order: 1, defaultValue: '', required: true, placeholder: '选择学位', options: ['大专', '本科', '硕士', '博士', 'MBA', '其他'] },
      { id: 'edu-major', name: '专业', type: FieldType.Text, order: 2, defaultValue: '', required: true, placeholder: '输入专业' },
      { id: 'edu-gpa', name: 'GPA', type: FieldType.Text, order: 3, defaultValue: '', required: false, placeholder: '输入GPA' },
      { id: 'edu-start', name: '开始时间', type: FieldType.Date, order: 4, defaultValue: '', required: true, placeholder: '选择开始时间' },
      { id: 'edu-end', name: '结束时间', type: FieldType.Date, order: 5, defaultValue: '', required: false, placeholder: '选择结束时间' },
      { id: 'edu-courses', name: '课程', type: FieldType.TagList, order: 6, defaultValue: '', required: false, placeholder: '输入课程，回车添加' },
      { id: 'edu-honors', name: '荣誉', type: FieldType.TextArea, order: 7, defaultValue: '', required: false, placeholder: '输入荣誉奖项' },
    ],
  },
  {
    id: 'tpl-project',
    name: '项目经验',
    category: '经历',
    isPreset: true,
    createdAt: 0,
    updatedAt: 0,
    fields: [
      { id: 'proj-name', name: '项目名', type: FieldType.Text, order: 0, defaultValue: '', required: true, placeholder: '输入项目名称' },
      { id: 'proj-role', name: '角色', type: FieldType.Text, order: 1, defaultValue: '', required: false, placeholder: '输入项目角色' },
      { id: 'proj-time', name: '时间', type: FieldType.Text, order: 2, defaultValue: '', required: false, placeholder: '如 2023.01 - 2023.06' },
      { id: 'proj-tech', name: '技术栈', type: FieldType.TagList, order: 3, defaultValue: '', required: false, placeholder: '输入技术栈，回车添加' },
      { id: 'proj-description', name: '描述', type: FieldType.RichText, order: 4, defaultValue: '', required: true, placeholder: '输入项目描述' },
      { id: 'proj-link', name: '链接', type: FieldType.Link, order: 5, defaultValue: '', required: false, placeholder: '输入项目链接' },
      { id: 'proj-screenshot', name: '截图', type: FieldType.Image, order: 6, defaultValue: '', required: false, placeholder: '上传项目截图' },
    ],
  },
  {
    id: 'tpl-skill',
    name: '技能',
    category: '基础',
    isPreset: true,
    createdAt: 0,
    updatedAt: 0,
    fields: [
      { id: 'skill-name', name: '技能名', type: FieldType.Text, order: 0, defaultValue: '', required: true, placeholder: '输入技能名称' },
      { id: 'skill-level', name: '熟练度', type: FieldType.Rating, order: 1, defaultValue: '3', required: false, placeholder: '' },
    ],
  },
  {
    id: 'tpl-summary',
    name: '自我总结',
    category: '基础',
    isPreset: true,
    createdAt: 0,
    updatedAt: 0,
    fields: [
      { id: 'summary-text', name: '描述', type: FieldType.TextArea, order: 0, defaultValue: '', required: true, placeholder: '输入自我总结' },
    ],
  },
  {
    id: 'tpl-cert',
    name: '证书',
    category: '其他',
    isPreset: true,
    createdAt: 0,
    updatedAt: 0,
    fields: [
      { id: 'cert-name', name: '名称', type: FieldType.Text, order: 0, defaultValue: '', required: true, placeholder: '输入证书名称' },
      { id: 'cert-issuer', name: '颁发机构', type: FieldType.Text, order: 1, defaultValue: '', required: false, placeholder: '输入颁发机构' },
      { id: 'cert-date', name: '时间', type: FieldType.Date, order: 2, defaultValue: '', required: false, placeholder: '选择获得时间' },
      { id: 'cert-number', name: '编号', type: FieldType.Text, order: 3, defaultValue: '', required: false, placeholder: '输入证书编号' },
      { id: 'cert-link', name: '链接', type: FieldType.Link, order: 4, defaultValue: '', required: false, placeholder: '输入证书链接' },
    ],
  },
  {
    id: 'tpl-lang',
    name: '语言',
    category: '其他',
    isPreset: true,
    createdAt: 0,
    updatedAt: 0,
    fields: [
      { id: 'lang-name', name: '语言', type: FieldType.Text, order: 0, defaultValue: '', required: true, placeholder: '输入语言' },
      { id: 'lang-listening', name: '听说', type: FieldType.Select, order: 1, defaultValue: '', required: false, placeholder: '选择听说等级', options: ['精通', '熟练', '一般', '入门'] },
      { id: 'lang-reading', name: '读写', type: FieldType.Select, order: 2, defaultValue: '', required: false, placeholder: '选择读写等级', options: ['精通', '熟练', '一般', '入门'] },
    ],
  },
  {
    id: 'tpl-hobby',
    name: '兴趣爱好',
    category: '其他',
    isPreset: true,
    createdAt: 0,
    updatedAt: 0,
    fields: [
      { id: 'hobby-tags', name: '标签', type: FieldType.TagList, order: 0, defaultValue: '', required: true, placeholder: '输入兴趣爱好，回车添加' },
    ],
  },
];

// ========== 预设色彩方案 ==========
export const presetColorSchemes: ColorScheme[] = [
  {
    id: 'cs-professional-blue',
    name: '沉稳蓝',
    primary: '#1a56db',
    secondary: '#d1e0ff',
    background: '#ffffff',
    blockBackground: '#f8faff',
    textPrimary: '#1f2937',
    textSecondary: '#4b5563',
    textMuted: '#9ca3af',
    accent: '#2563eb',
    isPreset: true,
  },
  {
    id: 'cs-elegant-dark',
    name: '优雅深灰',
    primary: '#374151',
    secondary: '#e5e7eb',
    background: '#ffffff',
    blockBackground: '#f9fafb',
    textPrimary: '#111827',
    textSecondary: '#4b5563',
    textMuted: '#9ca3af',
    accent: '#6366f1',
    isPreset: true,
  },
  {
    id: 'cs-fresh-green',
    name: '清新绿',
    primary: '#059669',
    secondary: '#d1fae5',
    background: '#ffffff',
    blockBackground: '#f0fdf4',
    textPrimary: '#1f2937',
    textSecondary: '#4b5563',
    textMuted: '#9ca3af',
    accent: '#10b981',
    isPreset: true,
  },
  {
    id: 'cs-warm-orange',
    name: '活力橙',
    primary: '#ea580c',
    secondary: '#ffedd5',
    background: '#ffffff',
    blockBackground: '#fff7ed',
    textPrimary: '#1f2937',
    textSecondary: '#4b5563',
    textMuted: '#9ca3af',
    accent: '#f97316',
    isPreset: true,
  },
  {
    id: 'cs-creative-purple',
    name: '创意紫',
    primary: '#7c3aed',
    secondary: '#ede9fe',
    background: '#ffffff',
    blockBackground: '#faf5ff',
    textPrimary: '#1f2937',
    textSecondary: '#4b5563',
    textMuted: '#9ca3af',
    accent: '#8b5cf6',
    isPreset: true,
  },
  {
    id: 'cs-tech-cyan',
    name: '科技青',
    primary: '#0891b2',
    secondary: '#cffafe',
    background: '#ffffff',
    blockBackground: '#ecfeff',
    textPrimary: '#1f2937',
    textSecondary: '#4b5563',
    textMuted: '#9ca3af',
    accent: '#06b6d4',
    isPreset: true,
  },
  {
    id: 'cs-minimal-bw',
    name: '极简黑白',
    primary: '#111827',
    secondary: '#f3f4f6',
    background: '#ffffff',
    blockBackground: '#fafafa',
    textPrimary: '#111827',
    textSecondary: '#374151',
    textMuted: '#9ca3af',
    accent: '#111827',
    isPreset: true,
  },
  {
    id: 'cs-rose-pink',
    name: '玫瑰粉',
    primary: '#e11d48',
    secondary: '#ffe4e6',
    background: '#ffffff',
    blockBackground: '#fff1f2',
    textPrimary: '#1f2937',
    textSecondary: '#4b5563',
    textMuted: '#9ca3af',
    accent: '#f43f5e',
    isPreset: true,
  },
];
